[package]
name = "stats"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]



[[example]]
name = "random_chars"
path = "examples/random_chars.rs"

[dev-dependencies]
rand = "0.8.4"
